apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftp
        - containerPort: 20021
          name: ftp-data